// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRmPxMqvo_FDLKwK20GKuGqlF4ETJYjw',
    appId: '1:43211069826:web:acd721d597dc44a9ab579b',
    messagingSenderId: '43211069826',
    projectId: 'valid-heuristic-438615-g2',
    authDomain: 'valid-heuristic-438615-g2.firebaseapp.com',
    storageBucket: 'valid-heuristic-438615-g2.firebasestorage.app',
    measurementId: 'G-PG4WQV557Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJgpbQHDsaVlL2ku0zi2L0_k23asF5Xo',
    appId: '1:43211069826:android:ccdcb148de20cfbdab579b',
    messagingSenderId: '43211069826',
    projectId: 'valid-heuristic-438615-g2',
    storageBucket: 'valid-heuristic-438615-g2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRG8miYbqrvpW1K31BzoCAxF211VBuamw',
    appId: '1:43211069826:ios:c8c3bf8ab7f35289ab579b',
    messagingSenderId: '43211069826',
    projectId: 'valid-heuristic-438615-g2',
    storageBucket: 'valid-heuristic-438615-g2.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRG8miYbqrvpW1K31BzoCAxF211VBuamw',
    appId: '1:43211069826:ios:c8c3bf8ab7f35289ab579b',
    messagingSenderId: '43211069826',
    projectId: 'valid-heuristic-438615-g2',
    storageBucket: 'valid-heuristic-438615-g2.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByRmPxMqvo_FDLKwK20GKuGqlF4ETJYjw',
    appId: '1:43211069826:web:1241dcd17b3c63adab579b',
    messagingSenderId: '43211069826',
    projectId: 'valid-heuristic-438615-g2',
    authDomain: 'valid-heuristic-438615-g2.firebaseapp.com',
    storageBucket: 'valid-heuristic-438615-g2.firebasestorage.app',
    measurementId: 'G-7GLHH6JTXH',
  );
}
